version: '3'

services:
  mydb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: abc
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /home/proj/scripts/init.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: mydb
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: abc
      PYTHONUNBUFFERED: 1
    volumes:
      - "./:/home/proj/"
    depends_on:
      - mydb

